CREATE USER DNAONLINE
IDENTIFIED BY cubo123
DEFAULT TABLESPACE TS_DNAONLINE;

GRANT CREATE SESSION TO DNAONLINE;
GRANT CREATE TABLE TO DNAONLINE;
GRANT CREATE SEQUENCE TO DNAONLINE;
GRANT CREATE SYNONYM TO DNAONLINE;
GRANT CREATE PROCEDURE TO DNAONLINE;
GRANT UNLIMITED TABLESPACE TO DNAONLINE WITH ADMIN OPTION;