-- Create table
CREATE TABLE DNAONLINE.LAYOUT_ENTRADA
(
  ID_LAYOUT_ENTRADA NUMBER(8) NOT NULL,
  NM_LAYOUT_ENTRADA VARCHAR2(100) NOT NULL
)
TABLESPACE TS_DNAONLINE;
-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE DNAONLINE.LAYOUT_ENTRADA
  ADD CONSTRAINT PK_LAYOUT_ENTRADA 
  PRIMARY KEY (ID_LAYOUT_ENTRADA);