-- Create table
CREATE TABLE DNAONLINE.STATUS_CONTROLE_ARQ_ATENTO
(
  CD_STATUS_CONTROLE_ARQUIVO NUMBER(2)    NOT NULL,
  DS_STATUS_CONTROLE_ARQUIVO VARCHAR2(50) NOT NULL
)
TABLESPACE TS_DNAONLINE;
-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE DNAONLINE.STATUS_CONTROLE_ARQ_ATENTO
  ADD CONSTRAINT PK_STATUS_CONTROLE_ARQ_ATENTO 
  PRIMARY KEY (CD_STATUS_CONTROLE_ARQUIVO);