-- Create table
CREATE TABLE DNAONLINE.USUARIO_ATENTO
(
  DS_LOGIN             VARCHAR2(20) NOT NULL,
  DS_SENHA             VARCHAR2(20) NOT NULL,
  NM_USUARIO           VARCHAR2(60) NOT NULL,
  DS_CONFIRMACAO_SENHA VARCHAR2(20) NOT NULL,
  DS_EMAIL             VARCHAR2(60) NOT NULL,
  CD_TIPO_USUARIO      CHAR(1)      NOT NULL
)
TABLESPACE TS_DNAONLINE;
-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE DNAONLINE.USUARIO_ATENTO
  ADD CONSTRAINT PK_USUARIO_ATENTO 
  PRIMARY KEY (DS_LOGIN);