-- Create table
CREATE TABLE DNAONLINE.CONTROLE_ARQ_ATENTO
(
  ID_CONTROLE                 NUMBER(8)     NOT NULL,
  DT_REGISTRO                 DATE          NOT NULL,
  ID_LAYOUT_ENTRADA           NUMBER(8)     NOT NULL,
  ID_LAYOUT_SAIDA             NUMBER(8)     NOT NULL,
  NM_ARQUIVO_ENTRADA          VARCHAR2(100) NOT NULL,
  DT_INICIO_EXECUCAO          DATE          NULL,
  DT_TERMINO_EXECUCAO         DATE          NULL,
  QT_ITENS_RECEBIDOS          NUMBER(3)     NULL,
  QT_ITENS_EXPORTADOS         NUMBER(3)     NULL,
  CD_STATUS_CONTROLE_ARQUIVO  NUMBER(2)     NOT NULL,
  NM_ARQUIVO_SAIDA            VARCHAR2(200) NULL,
  NM_ARQUIVO_UNZIP            VARCHAR2(200) NULL,
  NM_ARQUIVO_DOWNLOAD         VARCHAR2(200) NULL,
  NM_ARQUIVO_ENTRADA_ORIGINAL VARCHAR2(100) NOT NULL,
  DS_LOGIN                    VARCHAR2(20)  NOT NULL
)
TABLESPACE TS_DNAONLINE;
-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE DNAONLINE.CONTROLE_ARQ_ATENTO
  ADD CONSTRAINT PK_CONTROLE_ARQ_ATENTO 
  PRIMARY KEY (ID_CONTROLE);
  
ALTER TABLE DNAONLINE.CONTROLE_ARQ_ATENTO
  ADD CONSTRAINT FK_CONT_ARQ_ATENTO_LAYOUT_ENT 
  FOREIGN KEY (ID_LAYOUT_ENTRADA)
  REFERENCES DNAONLINE.LAYOUT_ENTRADA (ID_LAYOUT_ENTRADA);
  
ALTER TABLE DNAONLINE.CONTROLE_ARQ_ATENTO
  ADD CONSTRAINT FK_CONT_ARQ_ATENTO_LAYOUT_SAI 
  FOREIGN KEY (ID_LAYOUT_SAIDA)
  REFERENCES DNAONLINE.LAYOUT_SAIDA (ID_LAYOUT_SAIDA);
  
ALTER TABLE DNAONLINE.CONTROLE_ARQ_ATENTO
  ADD CONSTRAINT FK_CONT_ARQ_ATENTO_STATUS_CONT 
  FOREIGN KEY (CD_STATUS_CONTROLE_ARQUIVO)
  REFERENCES DNAONLINE.STATUS_CONTROLE_ARQ_ATENTO (CD_STATUS_CONTROLE_ARQUIVO);
  
ALTER TABLE DNAONLINE.CONTROLE_ARQ_ATENTO
  ADD CONSTRAINT FK_CONT_ARQ_ATENTO_USUARIO 
  FOREIGN KEY (DS_LOGIN)
  REFERENCES DNAONLINE.USUARIO_ATENTO (DS_LOGIN);