CREATE OR REPLACE PACKAGE PKG_CONTROLE_ARQUIVO_ATENTO
AS
    PROCEDURE ATUALIZAR_STATUS_DOWNLOAD
    (
        P_ID_CONTROLE        IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE,
        P_NM_ARQUIVO_UNZIP   IN CONTROLE_ARQ_ATENTO.NM_ARQUIVO_UNZIP%TYPE,
        P_NM_ARQUIVO_SAIDA   IN CONTROLE_ARQ_ATENTO.NM_ARQUIVO_SAIDA%TYPE
    );

    PROCEDURE ATUALIZAR_STATUS_IMPORTACAO
    (
        P_ID_CONTROLE        IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE
    );

    PROCEDURE ATUALIZAR_STATUS_EXTRACAO
    (
        P_ID_CONTROLE        IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE
    );

    PROCEDURE ATUALIZAR_STATUS_EXPORTACAO
    (
        P_ID_CONTROLE        IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE
    );

    PROCEDURE ATUALIZAR_STATUS_UPLOAD
    (
        P_ID_CONTROLE         IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE,
        P_NM_ARQUIVO_DOWNLOAD IN CONTROLE_ARQ_ATENTO.NM_ARQUIVO_DOWNLOAD%TYPE
    );
    
    PROCEDURE ATUALIZAR_ENVIO_EMAIL
    (
        P_ID_CONTROLE        IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE
    );
    
    PROCEDURE ATUALIZAR_STATUS_ERRO_LAYOUT
    (
        P_ID_CONTROLE        IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE
    );
    
    PROCEDURE ATUALIZAR_STATUS_EXPURGADO
    (
        P_ID_CONTROLE        IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE
    );
    
    PROCEDURE VERIFICAR_LOGIN_USUARIO
    (
        P_DS_LOGIN        IN USUARIO_ATENTO.DS_LOGIN%TYPE,
        P_DS_SENHA        IN USUARIO_ATENTO.DS_SENHA%TYPE,
        RETORNO_LOGIN     OUT SYS_REFCURSOR
    );
    
    PROCEDURE LISTAR_CONTROLE_ARQUIVO
    (
        P_DS_LOGIN                  IN  VARCHAR2,
        RETORNO_CONTROLE_ARQUIVO    OUT SYS_REFCURSOR
    );
    
    PROCEDURE ATUALIZAR_CONTROLE_ARQUIVO
    (
        P_DT_REGISTRO                 IN CONTROLE_ARQ_ATENTO.DT_REGISTRO%TYPE,
        P_ID_LAYOUT_ENTRADA           IN CONTROLE_ARQ_ATENTO.ID_LAYOUT_ENTRADA%TYPE,
        P_ID_LAYOUT_SAIDA             IN CONTROLE_ARQ_ATENTO.ID_LAYOUT_SAIDA%TYPE,
        P_NM_ARQUIVO_ENTRADA          IN CONTROLE_ARQ_ATENTO.NM_ARQUIVO_ENTRADA%TYPE,
        P_NM_ARQUIVO_ENTRADA_ORIGINAL IN CONTROLE_ARQ_ATENTO.NM_ARQUIVO_ENTRADA_ORIGINAL%TYPE,
        P_DS_LOGIN                    IN CONTROLE_ARQ_ATENTO.DS_LOGIN%TYPE
    );
    
    PROCEDURE CRIAR_USUARIO_ATENTO
    (
        P_DS_LOGIN                    IN USUARIO_ATENTO.DS_LOGIN%TYPE,
        P_DS_SENHA                    IN USUARIO_ATENTO.DS_SENHA%TYPE,
        P_DS_CONFIRMACAO_SENHA        IN USUARIO_ATENTO.DS_CONFIRMACAO_SENHA%TYPE,
        P_NM_USUARIO                  IN USUARIO_ATENTO.NM_USUARIO%TYPE,
        P_DS_EMAIL                    IN USUARIO_ATENTO.DS_EMAIL%TYPE,
        P_CD_GRUPOS                   IN VARCHAR2,
        P_CD_TIPO_USUARIO             IN USUARIO_ATENTO.CD_TIPO_USUARIO%TYPE
    );
    
    PROCEDURE BAIXAR_ARQUIVO_POR_ID
    (
        P_ID_CONTROLE                 IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE,
        RETORNO_POR_ID                OUT SYS_REFCURSOR
    );
    
    PROCEDURE LISTAR_GRUPO_USUARIO
    (
        RETORNO_GRUPO_USUARIO    OUT SYS_REFCURSOR
    );
    
    PROCEDURE ATUALIZAR_GRUPO_USUARIO
    (
        P_NM_GRUPO_USUARIO_ATENTO     IN GRUPO_USUARIO_ATENTO.NM_GRUPO_USUARIO_ATENTO%TYPE,
        P_DS_GRUPO_USUARIO_ATENTO     IN GRUPO_USUARIO_ATENTO.DS_GRUPO_USUARIO_ATENTO%TYPE
    );
    
    PROCEDURE GERAR_RELATORIO
    (
        P_ID_CONTROLE        IN CONTROLE_ARQ_ATENTO.ID_CONTROLE%TYPE,
        RETORNO_RELATORIO    OUT SYS_REFCURSOR
    );
    
    PROCEDURE LISTAR_GRUPO_USUARIO_CKL
    (
        P_TIPO_USUARIO        IN VARCHAR2,
        P_DS_LOGIN            IN VARCHAR2,
        RETORNO_GRUPO_USUARIO OUT SYS_REFCURSOR
    );
    
    PROCEDURE LISTAR_USUARIOS
    (
        P_DS_LOGIN        IN  USUARIO_ATENTO.DS_LOGIN%TYPE,
        P_TIPO_USUARIO    IN  USUARIO_ATENTO.CD_TIPO_USUARIO%TYPE,
        RETORNO_USUARIOS  OUT SYS_REFCURSOR
    );
    
    PROCEDURE EDITAR_USUARIO
    (
        P_NM_USUARIO        IN USUARIO_ATENTO.NM_USUARIO%TYPE,
        P_DS_LOGIN          IN USUARIO_ATENTO.DS_LOGIN%TYPE,
        RETORNO_USUARIO     OUT SYS_REFCURSOR
    );
    
    PROCEDURE ATUALIZAR_USUARIO
    (
        P_DS_LOGIN           IN USUARIO_ATENTO.DS_LOGIN%TYPE,
        P_NM_NOVO_USUARIO    IN VARCHAR2,
        P_DS_NOVO_EMAIL      IN VARCHAR2,
        P_CD_GRUPOS          IN VARCHAR2
    );
    
    PROCEDURE LISTAR_MEMBROS_GRUPO
    (
        P_ID_GRUPO           IN GRUPO_USUARIO_ATENTO.ID_GRUPO_USUARIO_ATENTO%TYPE,
        RETORNO_GRUPO        OUT SYS_REFCURSOR
    );
    
    PROCEDURE EDITAR_GRUPO
    (
        P_NM_GRUPO          IN GRUPO_USUARIO_ATENTO.NM_GRUPO_USUARIO_ATENTO%TYPE,
        P_ID_GRUPO          IN GRUPO_USUARIO_ATENTO.ID_GRUPO_USUARIO_ATENTO%TYPE,
        RETORNO_GRUPO       OUT SYS_REFCURSOR
    );
    
    PROCEDURE ATUALIZAR_GRUPO
    (
        P_ID_GRUPO           IN GRUPO_USUARIO_ATENTO.ID_GRUPO_USUARIO_ATENTO%TYPE,
        P_NM_NOVO_GRUPO      IN VARCHAR2,
        P_DS_NOVA_DESCRICAO  IN VARCHAR2
    );
    
    PROCEDURE VERIFICAR_USUARIO_CONTROLE
    (
        P_DS_LOGIN           IN   CONTROLE_ARQ_ATENTO.DS_LOGIN%TYPE,
        RETORNO_USUARIO      OUT  SYS_REFCURSOR
    );
    
    PROCEDURE DELETAR_USUARIO
    (
        P_DS_LOGIN           IN USUARIO_ATENTO.DS_LOGIN%TYPE
    );
    
    PROCEDURE VERIFICAR_USUARIO_GRUPO
    (
        P_CD_GRUPO           IN USUARIO_ATENTO_GRUPO_USUARIO.ID_GRUPO_USUARIO_ATENTO%TYPE,
        RETORNO_CD_GRUPO     OUT SYS_REFCURSOR
    );
    
    PROCEDURE DELETAR_GRUPO
    (
        P_CD_GRUPO         IN GRUPO_USUARIO_ATENTO.ID_GRUPO_USUARIO_ATENTO%TYPE
    );
    
    PROCEDURE LISTAR_GRUPOS
    (
        P_DS_LOGIN            IN USUARIO_ATENTO.DS_LOGIN%TYPE,
        RETORNO_GRUPO         OUT SYS_REFCURSOR
    );
    
    PROCEDURE VERIFICAR_USUARIO
    (
        P_DS_LOGIN            IN USUARIO_ATENTO.DS_LOGIN%TYPE,
        RETORNO_USUARIO       OUT SYS_REFCURSOR
    );
    
END;